steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/coscup-cloud-workstation', '.' ]
images:
  - 'gcr.io/$PROJECT_ID/coscup-cloud-workstation'
options:
  logging: CLOUD_LOGGING_ONLY
